{% set name = "RingDecomposerLib" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}-pkg
  version: {{ version }}

source:
  url: https://github.com/rareylab/RingDecomposerLib/archive/refs/tags/v{{ version }}_rdkit.tar.gz
  sha256: 944b5816712a48bbf88aa25d4300ce11871ddf6e971218eac08f90ed2192f715
  patches:
    - patches/language_c.patch
    - patches/no_static_lib.patch
    - patches/export_all_symbols.patch

build:
  number: 3

outputs:
  - name: {{ name|lower }}
    script: build_lib.sh  # [unix]
    script: build_lib.bat  # [win]

    build:
      run_exports:
        - {{ pin_subpackage(name|lower, max_pin='x') }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - cmake
        - ninja

    test:
      commands:
        - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_PREFIX%\\bin\\{{ name }}.dll exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\\lib\\{{ name }}.lib exit 1  # [win]
        - test ! -f $PREFIX/lib/lib{{ name }}Static.a  # [unix]
        - if exist %LIBRARY_PREFIX%\\lib\\{{ name }}Static.lib exit 1  # [win]
        - test -f $PREFIX/include/{{ name }}.h  # [unix]
        - if not exist %LIBRARY_PREFIX%\\include\\{{ name }}.h exit 1  # [win]

{% if unix %}
  - name: {{ name|lower }}-python
    script: build_python.sh  # [unix]
    script: build_python.bat  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - cython                              # [build_platform != target_platform]
      host:
        - pip
        - python
        - cython
        - {{ name|lower }} =={{ version }}
      run:
        - python
        - {{ name|lower }} =={{ version }}

    test:
      imports:
        - py_rdl
        - py_rdl.wrapper
      requires:
        - pip
      commands:
        - pip check
{% endif %}

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: |
    Calculation of Unique Ring Families (URFs) and other cycle bases
    (Relevant Cycles (RC), Smallest Set of Smallest Rings (SSSR)).
  home: https://github.com/rareylab/RingDecomposerLib
  doc_url: https://ringdecomposerlib.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - awvwgk
  feedstock-name: {{ name|lower }}
